In [20]:
import numpy as np 
from sklearn.model_selection import train_test_split

In [21]:
x = np.arange(1,25).reshape(12,2)
y = np.array([0,1,1,0,1,0,0,1,1,0,1,0])
x 

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [23]:
x_train

array([[ 7,  8],
       [23, 24],
       [15, 16],
       [ 1,  2],
       [ 9, 10],
       [11, 12],
       [ 5,  6],
       [13, 14],
       [17, 18]])

In [24]:
y_test

array([1, 1, 0])